services:
  postgres:
    image: postgres:17-alpine
    container_name: sso-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sso
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: